added modal to select source documentation
arc53/DocsGPT pull request #103
Opened 2023-02-19 20:31 UTC by TaylorS15

added api/docs.ts to fetch default source docs
added new reducer to preferenceSlice
added button in navigation to open modal

2023-02-20 17:53 UTC, ajaythapliyal commented
Since docs are being fetched from the network. We should show something to represent loading state when Docs modal is launched in case of delay. Can be done in next PR.

2023-02-20 18:10 UTC, ajaythapliyal requested changes

2023-02-20 18:10 UTC, ajaythapliyal commented on frontend/src/api/docs.ts
> +}
Since functionality in this file is unique to preference feature, it could be moved inside `preference` folder. 
Something like this : https://github.com/arc53/DocsGPT/blob/main/frontend/src/conversation/conversationApi.ts

2023-02-20 18:10 UTC, ajaythapliyal commented on frontend/src/models/misc.ts
> +};
Since this type is unique to preference feature, it could be moved inside preference folder as well.

2023-02-20 18:10 UTC, ajaythapliyal commented on frontend/src/Navigation.tsx
> +    useState<ActiveState>(isSelectedDocsSet ? 'INACTIVE' : 'ACTIVE');
we gotta put the two modal opening in sequence, can do it in the next PR.

2023-02-20 18:10 UTC, ajaythapliyal commented on frontend/src/preferences/SelectDocsModal.tsx
> +  const [docs, setDocs] = useState<Doc[] | null>(null);
I am on the fence about where to put all of the docs collection inside component state or redux. On one hand it feels like its okay as long as curently selected doc is  in redux. On other hand, it feels like next upcoming feature(upload https://github.com/arc53/DocsGPT/issues/105) would require all docs to be in redux so that new doc could be added when user decides to upload a doc . Ill let @TaylorS15  and @dartpain  handle this one.

2023-02-20 18:17 UTC, dartpain commented on frontend/src/preferences/SelectDocsModal.tsx
> +  const [docs, setDocs] = useState<Doc[] | null>(null);
Agreed, because of upcoming feature i think its best if its in the redux

2023-02-20 19:18 UTC, TaylorS15 commented
Everything has been changed per comments except for navigation opening the modals in sequence.

2023-02-21 14:34 UTC, dartpain approved these changes

2023-02-21 14:34 UTC, merged