Bug: Hero and conversation responsiveness
arc53/DocsGPT pull request #1287
Opened 2024-10-09 15:14 UTC by Vaibhav91one

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix hero and conversation pages responsiveness

- **Why was this change needed?** (You can also link to an open issue here)

The UI was not correctly aligned 

- **Other information**:

2024-10-09 21:23 UTC, ManishMadan2882 commented
Hi @Vaibhav91one 
As mentioned in this [comment](https://github.com/arc53/DocsGPT/pull/1194#issuecomment-2394762692).
Make these changes related to **tablet screens** only:
- The input box can be wider 
- Tagline can be visible
***
Make sure that the desktop or mobile screens are not affected
***

2024-10-10 12:43 UTC, akadeepesh approved these changes

2024-10-22 20:51 UTC, ManishMadan2882 requested changes
@Vaibhav91one 
1. The gap around the tagline has increased
2. It looks wider on PC screen
![image](https://github.com/user-attachments/assets/52800135-02a4-462c-b772-7b6c6717d102)
3. This is how it looks on the cloud version
![image](https://github.com/user-attachments/assets/d8908c67-0a96-4f05-8b4c-4d318eab591a)
Please try not to alter the dimensions for the pc devices, and stick to making it wider on the tablet devices only.

2024-10-26 09:08 UTC, Vaibhav91one commented
Hi @ManishMadan2882 , did the requested changes. Tagline is visible in mobile devices, UI can accomodate tagline in mobile device version. Please review the changes and do tell if any changes are required.

2024-10-26 15:56 UTC, akadeepesh approved these changes

2024-11-25 12:38 UTC, closed without merging