Set model to not receive documents when empty is selected
arc53/DocsGPT pull request #1347
Opened 2024-10-20 19:12 UTC by areebniyas

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- Set model to not receive documents when empty is selected

**Why was this change needed?** (You can also link to an open issue here)

- Closes #948

2024-10-22 11:48 UTC, ManishMadan2882 commented
Hey @areebniyas 
Think the issue is not in the frontend, as the same payload is sent to the POST /stream.
Can make sure that it needs to be fixed in the backend(/application), as the class selected for none doc type is `ClassicRAG` and the chunks are also 2 which is also same for default selection.
In the issue description it is mentioned that the
`The behaviour should be the same as if Chunks processed per query is set to 0.`
Thanks!

2024-10-22 14:09 UTC, areebniyas commented
Hi @ManishMadan2882 , thank you for the input. Would any of below approaches be correct:
1. setting the default to `None`
2. or removing the default retriever

at: https://github.com/arc53/DocsGPT/blob/4dd0d65db432741adea8c52176367d1af6e14a75/application/retriever/retriever_creator.py#L12

2024-10-22 19:46 UTC, ManishMadan2882 commented
Actually I feel like we might need a fix in the /stream route
There is certain ambiguity in this route, we have active_docs and selected_docs, the condition which we are checking in this [line](https://github.com/arc53/DocsGPT/blob/88623754cfeba9a2d65d6fad44d0c2a13126d330/application/api/answer/routes.py#L306) should actually be checked for active_docs. All we need to do is:
* remove the selected_docs and stick to active_docs only
* pass null/None in case the None document is selected, so that we can remove isNoneDoc(from the frontend)
* The behaviour of None selection should be such that a ClassicRAG works with 0 chunks
* Considering the approaches you mentioned, we don't need to remove any of the retrievers or defaulting to null.
Thanks and please feel free to ask anything regarding this issue.

2024-10-23 15:36 UTC, areebniyas commented
Hi @ManishMadan2882 , added some changes you mentioned - [cb71729](https://github.com/arc53/DocsGPT/pull/1347/commits/cb71729545c0242d58ee0cd03c3ca7ed7910c05f). Let me know your feedback and what I could do next.
Thanks for the support.

2024-10-23 20:38 UTC, ManishMadan2882 requested changes
This doesn't seem to fix the issue, I tried few things and feel like a simpler way to handle is to add one condition check just before creating the retriever instance.
Something like this:
```
if "isNoneDoc" in data and data["isNoneDoc"] is True:
                chunks = 0
```
For now keep the `isNoneDoc`, but you can remove "selectedDocs" from the stream post(), as we don't use it anywhere further.
Thanks!

2024-10-23 23:43 UTC, areebniyas commented
@ManishMadan2882 Added requested changes via [724660e](https://github.com/arc53/DocsGPT/pull/1347/commits/724660e5774a90456ccc1283e35c2af8963ae22d). Anything I missed?

2024-10-24 12:24 UTC, ManishMadan2882 commented on application/api/answer/routes.py
> -                chunks = int(data.get("chunks", 2))
Please restore this line 310, as chunks need to be initialised

2024-10-24 13:28 UTC, areebniyas commented on application/api/answer/routes.py
> -                chunks = int(data.get("chunks", 2))
Resolved with [3d650d0](https://github.com/arc53/DocsGPT/pull/1347/commits/3d650d0fbffabe402954ebfc71e56ebb854ddcd6)

2024-10-24 13:36 UTC, ManishMadan2882 commented
@areebniyas there is an error, did you test it on your system before pushing?

2024-10-26 20:04 UTC, closed without merging