Improved edit message interface
arc53/DocsGPT pull request #1514
Opened 2024-12-27 09:12 UTC by ayaan-qadri

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Improved edit message interface and decreased right margin hover on message button
- **Why was this change needed?** (You can also link to an open issue here)
Fixes - #1513 
- **Other information**:

<details>
<summary>Before</summary>

![image](https://github.com/user-attachments/assets/5c4b07cb-c9a6-4dd0-b010-89aa5cf06970)

![image](https://github.com/user-attachments/assets/0dc2aec8-6a69-4c75-9c67-54ea4a215d05)

</details>

<details>
<summary>After</summary>

![image](https://github.com/user-attachments/assets/5863df2a-0f8e-4d5e-b960-1125ec7c154d)

![image](https://github.com/user-attachments/assets/380264a8-cae1-4cd8-b958-25b69de674da)

</details>

2024-12-28 19:10 UTC, ayaan-qadri commented
Just rebase for change commit message

2025-01-06 22:44 UTC, ManishMadan2882 requested changes
Thanks @ayaan-qadri

Few points on this PR
* The update button should be rounded (as before) to match the design.
* The edit button shifts to bottom on selecting the edit option
![image](https://github.com/user-attachments/assets/4da361be-b751-438d-999b-d7fe63f73ce8)

2025-01-12 11:56 UTC, ayaan-qadri commented
@ManishMadan2882 It is useless to show edit button when it is already in edit mode & made button as it was before (rounded-full)

2025-01-17 22:23 UTC, ManishMadan2882 commented
@ayaan-qadri It edit button should not be hanging at the bottom, that was the main concern. 
LGTM Now, Could you please fix merge conflict ?

2025-02-16 20:10 UTC, merged