docs: add comments
arc53/DocsGPT pull request #386
Opened 2023-10-03 15:18 UTC by bintangoding

-Documentation Improvements
- This change was necessary to improve code documentation and enhance its clarity for developers and contributors

2023-10-03 22:29 UTC, dartpain requested changes
Im very happy that you chose to contribute to docsgpt, I left a review with comments, I just think you need to comment things that add more value to a reader and not create unecessary burden of text. I suggest you check out application/api/answer/routes.py file I think it needs extra comments, this would be very appreciated.

2023-10-03 22:29 UTC, dartpain commented on application/app.py
> +# import necessary modules
This is probably unecessary

2023-10-03 22:29 UTC, dartpain commented on application/app.py
> +    # Temporary alias to handle PosixPath on Windows
Unecessary

2023-10-03 22:29 UTC, dartpain commented on application/app.py
> +# loading envirornment variables from a .env file
Same

2023-10-03 22:29 UTC, dartpain commented on application/app.py
> +# Create a Flask application instance
Unecessary

2023-10-03 22:29 UTC, dartpain commented on application/app.py
>          # Handle other cases or render the default page
Unecessary

2023-10-03 22:29 UTC, dartpain commented on application/app.py
> +# Start the flask application if this script is executed directly
Unecessary

2023-10-06 12:32 UTC, larinam commented
From my perspective all changes in this PR are excessive. 

```A good best practice to follow when writing comments in code is to describe the why, not the what. In general, good code should be self-explanatory in how it works, at least in isolation. Explain the reasoning behind the code, not just what the code is doing. This can help others understand the intent of the code.```

https://swimm.io/learn/code-collaboration/comments-in-code-best-practices-and-mistakes-to-avoid

2023-10-06 14:43 UTC, closed without merging