New Prompt text file
arc53/DocsGPT pull request #504
Opened 2023-10-08 07:29 UTC by ayan-joshi

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature , Added a new text file in the prompt named custom_prompt 

- **Why was this change needed?** (You can also link to an open issue here)
The changes enhance the prompt folder a new text file is explaining the different tasks which GPT can perform and helps the user with what input will provide what output.

- **Other information**:

Please merge my pull request after the check and add the hacktoberfest accepted label to the pull request hanks @dartpain

2023-10-08 17:39 UTC, dartpain commented
Thank you for you contribution.

I dont see how those prompts will be integrated or used within the application at a stage that we are in now. Currently backend requires {summaries} section in the prompt. and a single prompt not multiple examples. 

It seems to me that you want to help people customise prompts. I suggest that you exand this guide
https://docs.docsgpt.co.uk/Guides/Customising-prompts, located here https://github.com/arc53/DocsGPT/blob/main/docs/pages/Guides/Customising-prompts.md

I think this will be a usefule contribution in there

2023-10-08 17:50 UTC, ayan-joshi commented
> Thank you for you contribution.
> 
> I dont see how those prompts will be integrated or used within the application at a stage that we are in now. Currently backend requires {summaries} section in the prompt. and a single prompt not multiple examples.
> 
> It seems to me that you want to help people customise prompts. I suggest that you exand this guide https://docs.docsgpt.co.uk/Guides/Customising-prompts, located here https://github.com/arc53/DocsGPT/blob/main/docs/pages/Guides/Customising-prompts.md
> 
> I think this will be a usefule contribution in there

@dartpain That's great so May I start work on this file and commit it to this pull request itself?

2023-10-08 21:34 UTC, dartpain commented
Yes please, that exactly what I think will be great!
discard previous commit and just edit https://github.com/arc53/DocsGPT/blob/main/docs/pages/Guides/Customising-prompts.md
I think you can add much more value there.

Thank you!

2023-10-09 08:59 UTC, ayan-joshi commented
> Yes please, that exactly what I think will be great! discard previous commit and just edit https://github.com/arc53/DocsGPT/blob/main/docs/pages/Guides/Customising-prompts.md I think you can add much more value there.
> 
> Thank you!

As guided by you I have made the changes @dartpain

2023-10-09 22:35 UTC, dartpain commented
Currently the application is using chat_combine_prompt.txt as the main prompt. Please amend. and make sure suggested prompts are based on it:
You are a DocsGPT, friendly and helpful AI assistant by Arc53 that provides help with documents. You give thorough answers with code examples if possible.
Use the following pieces of context to help answer the users question. If its not relevant to the question, provide friendly responses.
You have access to chat history, and can use it to help answer the question.
When using code examples, use the following format:
```(language)
(code)
```
----------------
{summaries}

Thank you

2023-10-11 17:11 UTC, ayan-joshi commented
@dartpain have a look and merge if it's okay

2023-10-11 21:10 UTC, dartpain requested changes
Thank you, I left some comments on how we can improve this section

2023-10-11 21:10 UTC, dartpain commented on docs/pages/Guides/Customising-prompts.md
> +Thank you
Remove thank you part.
This was adressed to you in my message, sorry for confusion

2023-10-11 21:10 UTC, dartpain commented on docs/pages/Guides/Customising-prompts.md
> +
Can we add one more example
from here https://docs.docsgpt.co.uk/Guides/My-AI-answers-questions-using-external-knowledge

And maybe one check out the https://docs.anthropic.com/claude/docs/let-claude-say-i-dont-know
and https://docs.anthropic.com/claude/docs/ask-claude-to-think-step-by-step
https://docs.anthropic.com/claude/docs/break-tasks-into-subtasks

As a source of inspiration for one or two prompts with some comments next to them

2023-10-17 16:29 UTC, ayan-joshi commented
@dartpain if it's ok can you merge it

2023-10-22 15:17 UTC, dartpain approved these changes

2023-10-22 15:19 UTC, merged