Update CONTRIBUTING.md
arc53/DocsGPT pull request #542
Opened 2023-10-10 06:44 UTC by shruti-sen2004

- **What kind of change does this PR introduce?** 
-  Updated the contributing.md file . I have chandes the worjflow section and made it easy to understand.

- **Why was this change needed?** 
-  It will help anyone who is a first time contributor

- **Other information**:
- No

2023-10-10 11:37 UTC, dartpain requested changes
Include space

and remove <br>

Thank you!

2023-10-10 11:37 UTC, dartpain commented on CONTRIBUTING.md
> +### Workflow📈 :
Space between text and emoji

2023-10-10 11:37 UTC, dartpain commented on CONTRIBUTING.md
> +- Fork the repository <br>
no need for <br>

2023-10-10 11:53 UTC, shruti-sen2004 commented on CONTRIBUTING.md
> +### Workflow📈 :
okay

2023-10-10 11:53 UTC, shruti-sen2004 commented on CONTRIBUTING.md
> +- Fork the repository <br>
okay

2023-10-10 11:54 UTC, shruti-sen2004 commented
I have made the necessary changes .

2023-10-10 12:03 UTC, dartpain commented
The <br> is still present

2023-10-10 12:06 UTC, shruti-sen2004 commented
I have again updated it. Can you pleas check.

2023-10-10 12:06 UTC, dartpain commented
Sorry this is markdown, please bring back the work the

I mean that I only want you to remove < br > tag

2023-10-10 12:07 UTC, shruti-sen2004 commented
Okay I think ...now i got it. :)

2023-10-10 12:32 UTC, dartpain commented
There is one more br tag on line 50
thank you

2023-10-10 14:19 UTC, shruti-sen2004 commented
I have updated the file......Can you please check?

2023-10-11 02:18 UTC, shruti-sen2004 commented
Can you please merge it.
Thank you

2023-10-11 17:57 UTC, dartpain approved these changes

2023-10-11 17:57 UTC, merged