Adds contributing guidelines with steps
arc53/DocsGPT pull request #579
Opened 2023-10-12 09:10 UTC by ankur0904

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs update

- **Why was this change needed?** (You can also link to an open issue here)
Fixed: #578

- **Other information**:
This Pull Request aims to enhance our contributing guidelines and includes necessary code to improve the contributor experience. The updated guidelines provide clearer instructions and expectations for potential contributors, making it easier for them to participate effectively in this project. The code changes ensure the seamless integration of these guidelines into our repository.

2023-10-13 18:01 UTC, ankur0904 commented
@dartpain Please review the PR.

2023-10-14 18:48 UTC, dartpain requested changes
Perfect! Just one small change

2023-10-14 18:48 UTC, dartpain commented on CONTRIBUTING.md
> +     python -m pytest
Please mention that only people who make backend changes need to run tests.

2023-10-15 04:12 UTC, ankur0904 commented
@dartpain Done :)

2023-10-15 21:45 UTC, dartpain approved these changes

2023-10-15 21:46 UTC, merged

2023-10-15 21:46 UTC, dartpain commented
Thank you!

2023-10-16 03:47 UTC, ankur0904 commented
@dartpain Thank you too.