FIX: added script in package.json of docs and added instructions to run nextra-DocsGPT locally
arc53/DocsGPT pull request #615
Opened 2023-10-16 05:32 UTC by shelar1423

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix and docs update
- **Why was this change needed?** (You can also link to an open issue here)
To setup  Nextra-DocsGPT docs  locally 

- **Other information**:
addd missing script in package.json:
![image](https://github.com/arc53/DocsGPT/assets/82649533/b6a26acd-7f06-4878-bc37-da280528b736)

2023-10-16 17:46 UTC, dartpain requested changes
Good PR just please remove commandline word
Instead do
```bash
git clone https://github.com/arc53/DocsGPT.git

2023-10-16 17:46 UTC, dartpain commented on docs/README.md
> +commandline
Good PR just please remove commandline word
Instead do 
```bash
git clone https://github.com/arc53/DocsGPT.git
```

2023-10-16 17:52 UTC, shelar1423 commented
@dartpain i have already added ``` so i guess no need for bash , what say ?

2023-10-16 17:59 UTC, shelar1423 commented
done @dartpain

2023-10-17 18:21 UTC, dartpain approved these changes

2023-10-17 18:21 UTC, merged