Patch 2
arc53/DocsGPT pull request #675
Opened 2023-10-23 16:16 UTC by krishvsoni

- **What kind of change does this PR introduce?**  - docs update -
-  **Why was this change needed?** (You can also link to an open issue here
- ) Already yaml file of docker is given but it in quick start we need to give Docker official url for downloading according to user device. It will help to setup the docker will also save the time 

- **Other information**: - <img width="842" alt="image" src="https://github.com/krishvsoni/DocsGPT/assets/67964054/6622b77e-ee13-411a-9cac-9b0b9f5ca454">

2023-10-23 16:20 UTC, dartpain requested changes
Please check the changes

2023-10-23 16:20 UTC, dartpain commented on README.md
> -  <strong><a href="https://docsgpt.arc53.com/">DocsGPT</a></strong> is a cutting-edge open-source solution that streamlines the process of finding information in the project documentation. With its i
Why are you removing the link?

2023-10-23 16:20 UTC, dartpain commented on README.md
> -Say goodbye to time-consuming manual searches, and let <strong><a href="https://docsgpt.arc53.com/">DocsGPT</a></strong> help you quickly find the information you need. Try it out and see how it revo
Again

2023-10-23 16:20 UTC, dartpain commented on README.md
> -- [Book Demo 👋](https://airtable.com/appdeaL0F1qV8Bl2C/shrrJF1Ll7btCJRbP)
Should be book demo, and why are lines removed?

2023-10-23 16:20 UTC, dartpain commented on README.md
> -| Name                                                                  | Base Model  | Requirements (or similar) |
Table was cleaner, why change it?

2023-10-23 16:20 UTC, dartpain commented on README.md
> -- 🔍🔥 [Live preview](https://docsgpt.arc53.com/)
Why are emojis removed?

2023-10-23 16:20 UTC, dartpain commented on README.md
> -2. Create a `.env` file in your root directory and set the env variable `OPENAI_API_KEY` with your [OpenAI API key](https://platform.openai.com/account/api-keys) and `VITE_API_STREAMING` to true or f
Please explain this change?

2023-10-23 16:21 UTC, krishvsoni commented on README.md
> -2. Create a `.env` file in your root directory and set the env variable `OPENAI_API_KEY` with your [OpenAI API key](https://platform.openai.com/account/api-keys) and `VITE_API_STREAMING` to true or f
Wait I fix

2023-10-23 16:21 UTC, krishvsoni commented on README.md
> -2. Create a `.env` file in your root directory and set the env variable `OPENAI_API_KEY` with your [OpenAI API key](https://platform.openai.com/account/api-keys) and `VITE_API_STREAMING` to true or f
just a  min

2023-10-23 16:32 UTC, krishvsoni commented
Done✔️

2023-10-23 16:41 UTC, dartpain commented
Can you please link it to instruction on how to install docker not just a documentation website. Thank you!

2023-10-23 16:46 UTC, krishvsoni commented
I added install docker url

2023-10-24 13:06 UTC, krishvsoni commented
Hello, As we had conflicts before in the branch so I had resolved it, and as mentioned about downloading docker I had put the url in the Docker keyword in the README file.

2023-10-25 10:57 UTC, dartpain approved these changes

2023-10-25 10:57 UTC, merged