Updated Readme.md
arc53/DocsGPT pull request #717
Opened 2023-10-28 10:53 UTC by apu52

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs Update
- **Why was this change needed?** (You can also link to an open issue here)
Hello Sir/ma'am,
I have updated readme.md file
- **Other information**:
I have made some changes in the readme file
- I have updated some alignments
- Made some Bold font to some alphabets etc.

2023-10-28 10:54 UTC, apu52 commented
Hey @dartpain, could you take a look at the changes and merge the PR if everything looks good? Thanks!

2023-10-29 07:17 UTC, apu52 commented
Hey @dartpain, could you take a look at the changes and merge the PR if everything looks good? Thanks!

2023-10-30 00:39 UTC, dartpain requested changes
Just a small change

2023-10-30 00:39 UTC, dartpain commented on README.md
> +5. To stop, just run `Ctrl + C`.
No need to have 5. here

2023-10-30 07:27 UTC, closed without merging