Update sidebar UI and Logo
arc53/DocsGPT pull request #722
Opened 2023-10-28 22:02 UTC by lakshmi930

1. Feature: Updating the Sidebar UI and logo
2. Will partially close #720

2023-10-29 23:54 UTC, dartpain requested changes
Everything is good, just one minor change and ready to merge. Thank you!

2023-10-29 23:54 UTC, dartpain commented on frontend/src/conversation/ConversationBubble.tsx
No need to make changes here

2023-10-30 05:59 UTC, lakshmi930 commented on frontend/src/conversation/ConversationBubble.tsx
This was mentioned as part of the requirement in the issue to update the logo in the reply sent from DocsGPT:
![image](https://github.com/arc53/DocsGPT/assets/79132440/26ebb735-e262-4022-975a-465d3bf58a69)

2023-10-30 09:22 UTC, dartpain commented on frontend/src/conversation/ConversationBubble.tsx
My bad, the dino looks inverted

2023-10-30 09:23 UTC, dartpain commented on frontend/src/conversation/ConversationBubble.tsx
<img width="958" alt="Screenshot 2023-10-30 at 09 23 26" src="https://github.com/arc53/DocsGPT/assets/15183589/765a1e92-a462-44e9-a9ff-e1482ed1217a">

2023-10-30 10:13 UTC, lakshmi930 commented on frontend/src/conversation/ConversationBubble.tsx
Okay, let me check this.

2023-10-30 20:43 UTC, lakshmi930 commented on frontend/src/conversation/ConversationBubble.tsx
Updated @dartpain , can you please check again? Also, how to test the dark mode? I see the designs ready but no way to switch the mode on the ui.

2023-10-30 21:29 UTC, dartpain commented on frontend/src/conversation/ConversationBubble.tsx
No dark mode, but its ok, ill link backend

2023-10-30 21:53 UTC, dartpain approved these changes

2023-10-30 21:55 UTC, merged

2023-10-30 21:56 UTC, dartpain commented
Thank you so much!

2023-10-31 05:06 UTC, lakshmi930 commented
Thank you for the quick review and release too @dartpain. This was a great chance to work on Tailwind for me.