Update/docs improve and fixes
arc53/DocsGPT pull request #728
Opened 2023-10-29 22:22 UTC by ka1bi4

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Docs update.

- **Why was this change needed?** (You can also link to an open issue here)

Improving documentation as part of the hacktorberfest festival ;)

- **Other information**:

Improving the readability of the text and correcting minor typos.

2023-10-29 22:30 UTC, ka1bi4 commented
Hi,
Improving documentation as part of the hacktorberfest festival ;)

2023-10-30 00:47 UTC, dartpain requested changes
Just a minor change

2023-10-30 00:47 UTC, dartpain commented on docs/pages/Deploying/Quickstart.md
Please add that its bash here too please

2023-10-30 10:53 UTC, ka1bi4 commented on docs/pages/Deploying/Quickstart.md
Yeah! I also fixed some . in the end of commands and make links localhost

2023-10-30 10:55 UTC, ka1bi4 commented
@dartpain, thanks!
Done it

2023-10-30 13:19 UTC, dartpain approved these changes

2023-10-30 13:19 UTC, merged

2023-10-30 13:20 UTC, dartpain commented
Thank you!