Issue button to clean chat history
arc53/DocsGPT pull request #929
Opened 2024-04-18 16:52 UTC by TomasMatarazzo

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

BACKEND:

- I added this endpoint to delete all the conversations.

<img width="584" alt="image" src="https://github.com/arc53/DocsGPT/assets/86305411/cd3ecd27-32ab-4c24-af14-5246628f0cc4">

FRONTEND:

- I added a button next to the chats label, it is hidden if you dont have chats. Let me know if this is ok. 
- When you click the button it opens a pop up that asks if you want to delete all the conversations. For this pop up i used a component that you have in the project called Modal.

<img width="296" alt="image" src="https://github.com/arc53/DocsGPT/assets/86305411/92e4f065-b670-4ee1-a838-e937e5846270">

<img width="1470" alt="image" src="https://github.com/arc53/DocsGPT/assets/86305411/0bd80e5f-a588-4653-b77a-1821130a47e1">

- **Why was this change needed?** (You can also link to an open issue here)

https://github.com/arc53/DocsGPT/issues/927

2024-04-19 09:27 UTC, dartpain commented
Thank you for your PR.
I just have one design change request.
Can we put the button that triggers deletion into the Settings  > General menu.
The modal is great!

2024-04-22 19:36 UTC, TomasMatarazzo commented
I changed the button to settings

2024-04-26 02:41 UTC, TomasMatarazzo commented
Sure
- I changed the button as you said
![image](https://github.com/arc53/DocsGPT/assets/86305411/f1ac13d5-c6f8-4cb0-adf8-8c0f4eb047a1)
- About the backend , i thought the same at first. Now all the users are local what i did is hardcode the user_id to local idk if this the correct approach, let me know
![image](https://github.com/arc53/DocsGPT/assets/86305411/4abe17e3-54b9-4bfb-93f1-f09b79e31952)

2024-04-26 15:19 UTC, dartpain commented
Hey, there is a quick error on Vercel, please check it out, thank you.

TS2741: Property 'modalState' is missing in type '{ apiKey: string; chunks: any; selectedDocs: any; prompt: any; conversations: null; sourceDocs: { location: string; language: string; name: string; version: string; date: string; description: string; docLink: string; fullName: string; model: string; }[]; }' but required in type '{ apiKey: string; prompt: { name: string; id: string; type: string; }; selectedDocs: { location: string; name: string; language: string; version: string; description: string; fullName: string; date: string; docLink: string; model: string; } | null; chunks: string; sourceDocs: { ...; }[] | null; conversations: { ...;...'.

2024-04-27 14:09 UTC, TomasMatarazzo commented
Let me know if now works. Thanks

2024-04-29 10:02 UTC, dartpain requested changes
Just a tiny comment to remove console.log statement and we are happy to merge

2024-04-29 10:02 UTC, dartpain commented on frontend/src/Navigation.tsx
> +        console.log(conversations);
Please remove console log

2024-05-01 08:55 UTC, dartpain approved these changes

2024-05-01 08:57 UTC, dartpain approved these changes

2024-05-01 08:57 UTC, dartpain commented
Thank you so much!

2024-05-01 09:54 UTC, merged